=== merceaemil/apidocs-rw/schemas/mine-site/mine-site.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rwanda.gov.rw/schemas/mine-site/mine-site.json",
  "title": "MD.01 Mine Site",
  "description": "Mine Site entity - Primary entity for Rwanda Mineral Data Interoperability Standard",
  "type": "object",
  "required": [
    "icglrId",
    "addressCountry",
    "certificationStatus",
    "activityStatus",
    "mineSiteLocation",
    "mineral",
    "license",
    "owner",
    "allowedTags"
  ],
  "properties": {
    "icglrId": {
      "$ref": "../core/common.json#/definitions/MineSiteIdFormat",
      "description": "ICGLR Identification number - A unique mine site identification number to be used at the level of ICGLR member states. Will follow the rules established by ICGLR for reporting and should be present if the data record needs to be reported as-is to ICGLR. Format: CC-[Lat]-[Long]-NNNNN (e.g., RW-1.9641+30.0619-12345)"
    },
    "addressCountry": {
      "$ref": "../core/common.json#/definitions/ICGLRMemberState",
      "description": "The country where the Mine site is located. National rule: It will always be RW"
    },
    "nationalId": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "National Identification Number - A unique mine site identification number at the level of the country"
    },
    "certificationStatus": {
      "$ref": "../core/common.json#/definitions/CertificationStatus",
      "description": "Certification status: 0=Blue (Uninspected), 1=Green (Certified), 2=Yellow (Yellow-Flagged), 3=Red (Un-Certified)"
    },
    "activityStatus": {
      "$ref": "../core/common.json#/definitions/MiningActivityStatus",
      "description": "Mining Activity Status: 0=Abandoned, 1=Active, 2=Non-active"
    },
    "mineSiteLocation": {
      "$ref": "./mine-site-location.json",
      "description": "MD.08 Mine Site Location"
    },
    "mineral": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "../core/common.json#/definitions/MineralCode"
      },
      "description": "The type or types of Mineral(s) produced at the mine, including Designated Minerals. Takes values strictly from the HS Code classification. For designated minerals: 7108.12.00 (Gold), 2609.00.00 (Cassiterite), 2611.00.00 (Wolframite), 2615.90.00 (Columbite-Tantalite/Coltan)"
    },
    "license": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./license.json"
      },
      "description": "MD.02 License - Group of terms describing the license and its details. Every mine site has a License field, even when the mine site is unlicensed."
    },
    "owner": {
      "$ref": "../core/common.json#/definitions/BusinessEntity",
      "description": "MD.04 Business Entity - Owner"
    },
    "operator": {
      "type": "array",
      "items": {
        "$ref": "../core/common.json#/definitions/BusinessEntity"
      },
      "description": "MD.04 Business Entity - The identification and full details of the Mine Operator/s if different from the owner"
    },
    "inspection": {
      "type": "array",
      "items": {
        "$ref": "./inspection.json"
      },
      "description": "MD.07 Inspection"
    },
    "statusChange": {
      "type": "array",
      "items": {
        "$ref": "./status-history.json"
      },
      "description": "MD.10 Status History - The history of status changes"
    },
    "allowedTags": {
      "type": "integer",
      "description": "Allowed Tags - Allowed Number of Tags. Approved Tags (list of tag numbers). Specific for Rwanda, which allocates a list of tag numbers to each mine site"
    },
    "minesLocations": {
      "type": "array",
      "items": {
        "$ref": "../core/common.json#/definitions/Geolocalization"
      },
      "description": "Mine Locations - Geographic localization of the mine site, given in the format lat: -1.9641, long: 30.0619. Given in WGS 84 format. In decimal degree format, with 4 decimals. Specific for Rwanda"
    }
  }
}

=== merceaemil/apidocs-rw/examples/json/mine-site-example.json
{
  "icglrId": "RW-1.9641+30.0619-00001",
  "addressCountry": "RW",
  "nationalId": "RW-MINE-2024-001",
  "certificationStatus": 1,
  "activityStatus": 1,
  "mineSiteLocation": {
      "geolocalization": {
        "lat": -1.9641,
        "long": 30.0619
      },
    "nationalCadasterLocalization": "Rwanda Mining Cadaster - Sector 12, Block 5",
    "localGeographicDesignation": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "subnationalDivisionL2": "Nyaruguru District",
      "addressLocalityText": "Muhanga"
    },
    "polygon": {
      "type": "Polygon",
      "coordinates": [[[30.0619, -1.9641], [30.0623, -1.9641], [30.0623, -1.9637], [30.0619, -1.9637], [30.0619, -1.9641]]]
    },
    "altitude": 1500
  },
  "mineral": [
    "7108.12.00",
    "2611.00.00"
  ],
  "license": [
    {
      "licenseType": "mining_license",
      "licenseId": "RW-ML-2024-001",
      "owner": {
        "identifier": "COMP-RW-001",
        "name": "Rwanda Mining Corporation Ltd",
        "legalAddress": {
          "country": "RW",
          "subnationalDivisionL1": "RW-01",
          "subnationalDivisionL1Text": "City of Kigali",
          "addressLocalityText": "Kigali"
        },
        "physicalAddress": {
          "country": "RW",
          "subnationalDivisionL1": "RW-01",
          "subnationalDivisionL1Text": "City of Kigali",
          "addressLocalityText": "Kigali"
        },
        "tin": "123456789",
        "businessType": "Limited Liability Company",
        "contactDetails": {
          "legalRepresentative": "John Doe",
          "contactPhoneNumber": "+250788123456",
          "contactEmail": "contact@rwandamining.rw"
        }
      },
      "grantedDate": "2024-01-15",
      "expiringDate": "2029-01-14",
      "licenseStatus": "1",
      "coveredCommodities": [
        "7108.12.00",
        "2611.00.00"
      ]
    }
  ],
  "owner": {
    "identifier": "COMP-RW-001",
    "name": "Rwanda Mining Corporation Ltd",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "123456789",
    "businessType": "Limited Liability Company",
    "contactDetails": {
      "legalRepresentative": "John Doe",
      "contactPhoneNumber": "+250788123456",
      "contactEmail": "contact@rwandamining.rw"
    }
  },
  "allowedTags": 100,
  "operator": [],
  "inspection": [
    {
      "inspectionId": "PS-2024-03-15-10-30",
      "inspectionDate": "2024-03-15",
      "inspectionResponsible": "Rwanda Mines, Petroleum and Gas Board - Peter Smith",
      "inspectionResult": 1,
      "inspectionReport": "https://reports.rmb.rw/inspections/PS-2024-03-15-10-30.pdf",
      "inspectionPurpose": "Annual certification inspection",
      "inspectionResults": "Mine site meets all ICGLR certification requirements. No violations found.",
      "inspectorName": "Peter Smith",
      "inspectorPosition": "Senior Mining Inspector",
      "governmentAgency": "Ministry of Mines, Rwanda",
      "governmentId": "GOV-RW-001"
    }
  ],
  "statusChange": [
    {
      "dateOfChange": "2024-03-15",
      "newStatus": 1
    }
  ]
}

=== merceaemil/apidocs-rw/examples/json/mine-site-with-multiple-inspections-example.json
{
  "icglrId": "RW-1.9403+29.8739-00001",
  "addressCountry": "RW",
  "nationalId": "RW-MINE-2024-001",
  "certificationStatus": 2,
  "activityStatus": 1,
  "mineSiteLocation": {
      "geolocalization": {
        "lat": -1.9403,
        "long": 29.8739
      },
    "nationalCadasterLocalization": "Rwanda Mining Cadaster - Sector 12, Block 5",
    "localGeographicDesignation": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "subnationalDivisionL2": "Nyaruguru District",
      "addressLocalityText": "Muhanga"
    },
    "polygon": {
      "type": "Polygon",
      "coordinates": [[[29.8739, -1.9403], [29.8743, -1.9403], [29.8743, -1.9399], [29.8739, -1.9399], [29.8739, -1.9403]]]
    },
    "altitude": 1500
  },
  "mineral": [
    "2615.90.00",
    "2609.00.00"
  ],
  "license": [
    {
      "licenseType": "mining_license",
      "licenseId": "RW-ML-2024-001",
      "owner": {
        "identifier": "COMP-RW-001",
        "name": "Rwanda Mining Corporation",
        "legalAddress": {
          "country": "RW",
          "subnationalDivisionL1": "RW-01",
          "subnationalDivisionL1Text": "City of Kigali",
          "addressLocalityText": "Kigali"
        },
        "physicalAddress": {
          "country": "RW",
          "subnationalDivisionL1": "RW-01",
          "subnationalDivisionL1Text": "City of Kigali",
          "addressLocalityText": "Kigali"
        },
        "tin": "RW123456789",
        "businessType": "Limited Liability Company",
        "contactDetails": {
          "legalRepresentative": "Jean Dupont",
          "contactPhoneNumber": "+250788123456",
          "contactEmail": "contact@rwandamining.rw"
        }
      },
      "grantedDate": "2024-01-15",
      "expiringDate": "2029-01-14",
      "licenseStatus": "1",
      "coveredCommodities": [
        "2615.90.00",
        "2609.00.00"
      ]
    }
  ],
  "owner": {
    "identifier": "COMP-RW-001",
    "name": "Rwanda Mining Corporation",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "RW123456789",
    "businessType": "Limited Liability Company",
    "contactDetails": {
      "legalRepresentative": "Jean Dupont",
      "contactPhoneNumber": "+250788123456",
      "contactEmail": "contact@rwandamining.rw"
    }
  },
  "allowedTags": 100,
  "operator": [],
  "inspection": [
    {
      "inspectionId": "PS-2024-01-15-10-30",
      "inspectionDate": "2024-01-15",
      "inspectionResponsible": "Rwanda Mines, Petroleum and Gas Board - Peter Smith",
      "inspectionResult": 2,
      "inspectionReport": "https://reports.rmb.rw/inspections/PS-2024-01-15-10-30.pdf",
      "inspectionPurpose": "Initial certification inspection",
      "inspectionResults": "Mine site meets all certification requirements. No violations found. Recommended for Green status.",
      "inspectorName": "Peter Smith",
      "inspectorPosition": "Senior Mining Inspector",
      "governmentAgency": "Rwanda Mines, Petroleum and Gas Board",
      "governmentId": "GOV-RW-001"
    },
    {
      "inspectionId": "PS-2024-03-20-14-00",
      "inspectionDate": "2024-03-20",
      "inspectionResponsible": "Rwanda Mines, Petroleum and Gas Board - Peter Smith",
      "inspectionResult": 1,
      "inspectionReport": "https://reports.rmb.rw/inspections/PS-2024-03-20-14-00.pdf",
      "inspectionPurpose": "Follow-up inspection",
      "inspectionResults": "Minor violations found in safety procedures. Corrective actions required. Status changed to Yellow.",
      "inspectorName": "Peter Smith",
      "inspectorPosition": "Senior Mining Inspector",
      "governmentAgency": "Rwanda Mines, Petroleum and Gas Board",
      "governmentId": "GOV-RW-001"
    }
  ],
  "statusChange": [
    {
      "dateOfChange": "2024-01-15",
      "newStatus": 1
    },
    {
      "dateOfChange": "2024-03-20",
      "newStatus": 2
    }
  ]
}
