=== merceaemil/apidocs-rw/schemas/export-certificate/export-certificate.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rwanda.gov.rw/schemas/export-certificate/export-certificate.json",
  "title": "MD.03 Export Certificate",
  "description": "ICGLR Export Certificate entity",
  "type": "object",
  "required": [
    "issuingCountry",
    "identifier",
    "exporter",
    "importer",
    "lotNumber",
    "typeOfOre",
    "lotWeight",
    "lotWeightUOM",
    "lotGrade",
    "mineralOrigin",
    "customsValue",
    "dateOfShipment",
    "memberStateIssuingAuthority",
    "nameOfVerifier",
    "positionOfVerifier",
    "dateOfVerification",
    "nameOfValidator",
    "dateOfIssuance",
    "dateOfExpiration",
    "certificateFile"
  ],
  "properties": {
    "issuingCountry": {
      "$ref": "../core/common.json#/definitions/ICGLRMemberState",
      "description": "The ISO 3166-1 alpha-2 code of the issuing country. National rule: It will always be RW"
    },
    "identifier": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "Serial number - A unique serial number identifying the Certificate. A unique combination of digits and letters from the standard Latin alphabet, unique in the country, starting with the ISO 3166-1 alpha-2 – two-letter country code (e.g., RW2324A2)"
    },
    "exporter": {
      "$ref": "../core/common.json#/definitions/BusinessEntity",
      "description": "MD.04 Business Entity - A group of business terms providing information about the Exporter. Includes: The name, legal address and physical address of the exporter, as well as any other information required to identify the exporter"
    },
    "importer": {
      "$ref": "../core/common.json#/definitions/BusinessEntity",
      "description": "MD.04 Business Entity - The name, legal address and physical address of the importer, as well as any other information required to identify the importer"
    },
    "lotNumber": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "The exporter's unique lot number or export order number for the lot. References MD.12 Lot"
    },
    "designatedMineralDescription": {
      "type": "string",
      "description": "A description of the Designated Mineral, including the type of ore or concentrate, weight and grade of the lot. Free textual description"
    },
    "typeOfOre": {
      "$ref": "../core/common.json#/definitions/MineralCode",
      "description": "Type of ore - MDC.03 Mineral"
    },
    "lotWeight": {
      "$ref": "../core/common.json#/definitions/Decimal",
      "description": "Lot Weight - Numeric format, accepting fractional value, should always be read together with the Lot Weight Unit of Measure. Should be a positive number (>0) with a maximum of 3 decimals (0.000)"
    },
    "lotWeightUOM": {
      "$ref": "../core/common.json#/definitions/UnitOfMeasurement",
      "description": "Lot Weight Unit of Measure - The unit of measure shall be chosen from the lists in UN/ECE Recommendation N°. 20 'Codes for Units of Measure Used in International Trade'. Can take value from a strict list of UOMs"
    },
    "lotGrade": {
      "type": "string",
      "description": "Lot Grade - Grade expression might vary depending on the mineral"
    },
    "mineralOrigin": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "The national origin of the material (either the name of the country, or \"mixed\" in the case of lots containing material from two or more nations mixed together). One or more country identifiers, separated by one space character (e.g., CD BI RW). In case the origin is not known, the character zero (0) will be used to illustrate this. Validation: Can be a single 2-letter country code (e.g., BI), array of 2-letter country codes separated by semicolon (e.g., BI;TZ;CD), or zero (0) for unknown origin. Zero can be combined in an array (e.g., BI;TZ;0) showing that the mineral comes from at least 3 sources, from which 2 are known."
    },
    "customsValue": {
      "type": "string",
      "description": "The declared Customs value in USD of the Lot (explicit requirement according to Appendix C of RCM Manual). Use Currency code of 3 letters (ISO 4217) and value Decimal format, separated by one space character. Alternatively, it can be Decimal considering that it should always be given in USD"
    },
    "dateOfShipment": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "The date the lot is planned to be shipped. As the export certificate is issued before the shipment occurs, the actual date of shipment might be different."
    },
    "shipmentRoute": {
      "type": "string",
      "description": "The shipment route - ISO 3166 alpha-2 (array of countries separated by a comma without spaces, e.g., CD,TZ,BI) or array of ISO 3166 alpha-2 and ISO 3166 alpha-3 that includes also standardized denominations of regions"
    },
    "transportCompany": {
      "type": "string",
      "description": "The transport company responsible for transporting the shipment, if known"
    },
    "memberStateIssuingAuthority": {
      "type": "string",
      "description": "Member State Issuing authority"
    },
    "nameOfVerifier": {
      "type": "string",
      "description": "Name of the Rwandan representative responsible for verifying the documentation associated the export with the export and recommending the issuance of an ICGLR Regional Certificate"
    },
    "positionOfVerifier": {
      "type": "string",
      "description": "Position of the Rwandan representative responsible for verifying the documentation associated the export with the export and recommending the issuance of an ICGLR Regional Certificate"
    },
    "idOfVerifier": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "Identification number (where available) of the Rwandan representative responsible for verifying the documentation associated the export with the export and recommending the issuance of an ICGLR Regional Certificate"
    },
    "dateOfVerification": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "The date the lot is verified by the Rwandan representative"
    },
    "nameOfValidator": {
      "type": "string",
      "description": "The name of the Rwandan representative empowered to countersign the Certificate to render it valid"
    },
    "dateOfIssuance": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "The date that the Certificate is countersigned (Certificate is valid from this date)"
    },
    "dateOfExpiration": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "The date that the Certificate expires, or the validity period of the Certificate. Between date of issuance and date of expiration should not be more than 90 days"
    },
    "certificateFile": {
      "type": "string",
      "description": "The certificate as file. Should have value from a limited list of MIME types: application/pdf, image/png, image/jpeg"
    }
  }
}

=== merceaemil/apidocs-rw/examples/json/export-certificate-example.json
{
  "issuingCountry": "RW",
  "identifier": "RW-EXP-2024-001",
  "exporter": {
    "identifier": "COMP-RW-001",
    "name": "Rwanda Mining Corporation Ltd",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "123456789",
    "businessType": "Limited Liability Company",
    "contactDetails": {
      "legalRepresentative": "John Doe",
      "contactPhoneNumber": "+250788123456",
      "contactEmail": "contact@rwandamining.rw"
    }
  },
  "importer": {
    "identifier": "COMP-RW-003",
    "name": "Rwanda Export Trading Company",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "987654321",
    "businessType": "Trading Company",
    "contactDetails": {
      "legalRepresentative": "Jane Smith",
      "contactPhoneNumber": "+250788999888",
      "contactEmail": "contact@rwandaexport.rw"
    }
  },
  "lotNumber": "LOT-RW-2024-001",
  "designatedMineralDescription": "Cassiterite concentrate, 1000kg, 45% Sn",
  "typeOfOre": "2609.00.00",
  "lotWeight": 1000.0,
  "lotWeightUOM": "KGM",
  "lotGrade": "45%",
  "mineralOrigin": "RW",
  "customsValue": "USD 85000.00",
  "dateOfShipment": "2024-04-15",
  "shipmentRoute": "RW,KE,TZ",
  "transportCompany": "East Africa Logistics",
  "memberStateIssuingAuthority": "Ministry of Trade and Industry, Rwanda",
  "nameOfVerifier": "Peter Smith",
  "positionOfVerifier": "Senior Mining Inspector",
  "idOfVerifier": "GOV-RW-001",
  "dateOfVerification": "2024-04-10",
  "nameOfValidator": "Mary Johnson",
  "dateOfIssuance": "2024-04-12",
  "dateOfExpiration": "2024-07-11",
  "certificateFile": "https://certificates.rmb.rw/RW-EXP-2024-001.pdf"
}
