=== merceaemil/apidocs-rw/schemas/chain-of-custody/lot.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rwanda.gov.rw/schemas/chain-of-custody/lot.json",
  "title": "MD.12 Lot",
  "description": "Lot entity - The holder of a quantity of minerals that are mined. The Lot is initially constituted at the Mine Site. In local/national practice, the 'Lot' can be named in different ways, as Bag, as Package, etc. However, the packaging format is not relevant to the data model used for tracing. The same format of the definition of a Lot is intended for transport, processing, or sale. In the CoC, the 'lot' is redefined whenever there is a transformation involving aggregation or disaggregation.",
  "type": "object",
  "required": [
    "lotNumber",
    "dateRegistration",
    "timeRegistration",
    "creator",
    "mineral",
    "concentration",
    "mass",
    "unitOfMeasurement",
    "creatorRole",
    "price",
    "originatingOperation"
  ],
  "properties": {
    "lotNumber": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "Lot number given by the CoC actor from which the lot originates. It is not necessarily captured in a Tag."
    },
    "dateRegistration": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "Date of registration - Date when the registration was created"
    },
    "timeRegistration": {
      "$ref": "../core/common.json#/definitions/Time",
      "description": "Time of registration - Time (hh:mm:ss) when the registration was created. Should be automatically generated by the software system that assists the registration of the Lot data record"
    },
    "creator": {
      "$ref": "../core/common.json#/definitions/BusinessEntity",
      "description": "MD.04 Business Entity - Lot Creator - The business entity that created the lot. Equivalent to current custodian."
    },
    "mineral": {
      "$ref": "../core/common.json#/definitions/MineralCode",
      "description": "MDC.03 Mineral - Identifier of the mineral contained in the bag"
    },
    "concentration": {
      "$ref": "../core/common.json#/definitions/Decimal",
      "description": "Percentual concentration - Approximate mineral concentration (grade), in percent"
    },
    "mass": {
      "$ref": "../core/common.json#/definitions/Decimal",
      "description": "Lot weight - Weight of the Lot"
    },
    "packageType": {
      "type": "string",
      "description": "Type of packaging - Describes how the Lot is packaged (as bag, barrel, container, etc)"
    },
    "nrOfPackages": {
      "$ref": "../core/common.json#/definitions/Decimal",
      "description": "Number of packages - In case a lot is composed of more packages"
    },
    "unitOfMeasurement": {
      "$ref": "../core/common.json#/definitions/UnitOfMeasurement",
      "description": "MDC.07 Unit of measurement - The unit of measure shall be chosen from the lists in UN/ECE Recommendation NÂ°. 20 'Codes for Units of Measure Used in International Trade'. Can take value from a strict list of UOMs"
    },
    "mineSiteId": {
      "$ref": "../core/common.json#/definitions/MineSiteIdFormat",
      "description": "MD.01 Mine Site - Identifier of the mine site where the ore was extracted. REQUIRED when the Originating operation is Production"
    },
    "miner": {
      "type": "string",
      "description": "Miner's name - The name of the miner who represented the team. REQUIRED when the Originating operation is Production. Specific for Rwanda"
    },
    "creatorRole": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "../core/common.json#/definitions/CoCRole"
      },
      "description": "MDC.05 CoC Roles - The role(s) of the entity in the CoC"
    },
    "recipient": {
      "$ref": "../core/common.json#/definitions/BusinessEntity",
      "description": "MD.04 Business Entity - Lot Recipient - The identification of the customer or recipient, including name, address and site location and government identification number"
    },
    "price": {
      "$ref": "../core/common.json#/definitions/Decimal",
      "description": "Price per UOM - Required in Rwanda as $/kg"
    },
    "originatingOperation": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "../core/common.json#/definitions/OriginatingOperation"
      },
      "description": "MDC.06 Originating operations - The operation(s) that determined the creation of the Lot. Can be combined (e.g., 2;3;4 for Purchase, Combination, Processing)"
    },
    "inputLot": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "Reference to input lot(s) - MD.12 Lot",
        "properties": {
          "lotNumber": {
            "$ref": "../core/common.json#/definitions/Identifier"
          }
        }
      },
      "description": "Lots that form this lot - A collection of lots that were used to aggregate this lot. If there is no transformation, except for changing actors in the CoC, the inputLot is itself. This attribute does not exist for the initial Lot (the one registered at the Mine Site). References MD.12 Lot"
    },
    "tag": {
      "$ref": "./tag.json",
      "description": "MD.11 Tag - Associated tag. REQUIRED when the Originating operation is Production"
    },
    "taxPaid": {
      "type": "array",
      "items": {
        "$ref": "./tax.json"
      },
      "description": "MD.13 Tax - Values and details of all taxes, fees or royalties paid to government for the purpose of extraction, trade, transport or processing of the lot, along with any other payments made to governmental officials"
    },
    "dateSealed": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "Date when sealed - The date when the lot is sealed"
    },
    "dateShipped": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "Date when shipped - The date when the lot is shipped"
    },
    "purchaseNumber": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "Purchase number - A unique purchase order number for the external purchase, in case it is applicable"
    },
    "purchaseDate": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "Purchase date - The date of the purchase, if applicable"
    },
    "responsibleStaff": {
      "type": "string",
      "description": "Responsible staff - Name of the responsible staff person(s) who accepted the Designated Mineral Lot and verified the origin. Can be a string including multiple names."
    },
    "dateIn": {
      "$ref": "../core/common.json#/definitions/Date",
      "description": "Date received - The date when the processor took possession of the lot (does not apply in the first step of the CoC)"
    },
    "transportationMethod": {
      "type": "string",
      "description": "Transportation method - The method by which the Lot was transported from mine site to processor"
    },
    "transportationRoute": {
      "type": "string",
      "description": "Transportation route - The transportation route used for the shipment of the incoming Lot"
    },
    "transportCompany": {
      "type": "string",
      "description": "Transport Company - transport company responsible for transporting the shipment"
    },
    "exportCertificateId": {
      "$ref": "../core/common.json#/definitions/Identifier",
      "description": "MD.03 Export Certificate - An ICGLR Certificate number, if for export"
    }
  }
}

=== merceaemil/apidocs-rw/examples/json/lot-example.json
{
  "lotNumber": "LOT-RW-2024-001",
  "dateRegistration": "2024-03-20",
  "timeRegistration": "10:30:00",
  "creator": {
    "identifier": "COMP-RW-001",
    "name": "Rwanda Mining Corporation Ltd",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "123456789",
    "businessType": "Limited Liability Company",
    "contactDetails": {
      "legalRepresentative": "John Doe",
      "contactPhoneNumber": "+250788123456",
      "contactEmail": "contact@rwandamining.rw"
    }
  },
  "mineral": "7108.12.00",
  "concentration": 45.5,
  "mass": 1000.0,
  "packageType": "bag",
  "nrOfPackages": 1,
  "unitOfMeasurement": "KGM",
  "mineSiteId": "RW-1.9641+30.0619-00001",
  "creatorRole": [1],
  "recipient": {
    "identifier": "COMP-RW-002",
    "name": "Rwanda Processing Center",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "addressLocalityText": "Huye"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "addressLocalityText": "Huye"
    },
    "tin": "987654321",
    "businessType": "Processing Company",
    "contactDetails": {
      "legalRepresentative": "Alice Brown",
      "contactPhoneNumber": "+250788654321",
      "contactEmail": "contact@rwandaprocessing.rw"
    }
  },
  "price": 45.50,
  "originatingOperation": [1],
  "tag": {
    "identifier": "TAG-RW-2024-001",
    "issuer": {
      "identifier": "GOV-RW-001",
      "name": "Ministry of Mines, Rwanda",
      "legalAddress": {
        "country": "RW",
        "subnationalDivisionL1": "RW-01",
        "subnationalDivisionL1Text": "City of Kigali",
        "addressLocalityText": "Kigali"
      },
      "physicalAddress": {
        "country": "RW",
        "subnationalDivisionL1": "RW-01",
        "subnationalDivisionL1Text": "City of Kigali",
        "addressLocalityText": "Kigali"
      },
      "tin": "GOV-001",
      "businessType": "Government Agency",
      "contactDetails": {
        "legalRepresentative": "Government Representative",
        "contactPhoneNumber": "+250788000000",
        "contactEmail": "mines@gov.rw"
      }
    },
    "issueDate": "2024-03-20",
    "issueTime": "10:30:00",
    "representativeRMB": "John Mwangi",
    "tagType": "QR Code"
  },
  "miner": "Jean Baptiste",
  "taxPaid": [
    {
      "taxType": "Mining Royalty",
      "taxAmount": 5000.00,
      "currency": "USD",
      "taxAuthority": "Ministry of Mines",
      "taxPaidDate": "2024-03-20",
      "receiptReference": "REC-2024-001"
    },
    {
      "taxType": "Export Tax",
      "taxAmount": 2500.00,
      "currency": "USD",
      "taxAuthority": "Rwanda Revenue Authority",
      "taxPaidDate": "2024-03-20",
      "receiptReference": "REC-2024-002"
    }
  ],
  "dateSealed": "2024-03-20",
  "dateShipped": "2024-03-22",
  "responsibleStaff": "John Doe, Site Manager"
}

=== merceaemil/apidocs-rw/examples/json/lot-transformation-example.json
{
  "lotNumber": "LOT-RW-PROC-2024-001",
  "dateRegistration": "2024-03-25",
  "timeRegistration": "14:00:00",
  "creator": {
    "identifier": "COMP-RW-002",
    "name": "Rwanda Processing Center",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "addressLocalityText": "Huye"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-02",
      "subnationalDivisionL1Text": "Southern",
      "addressLocalityText": "Huye"
    },
    "tin": "987654321",
    "businessType": "Processing Company",
    "contactDetails": {
      "legalRepresentative": "Alice Brown",
      "contactPhoneNumber": "+250788654321",
      "contactEmail": "contact@rwandaprocessing.rw"
    }
  },
  "mineral": "2609.00.00",
  "concentration": 48.0,
  "mass": 950.0,
  "packageType": "container",
  "unitOfMeasurement": "KGM",
  "price": 48.50,
  "creatorRole": [4],
  "recipient": {
    "identifier": "COMP-RW-003",
    "name": "Rwanda Export Trading Company",
    "legalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "physicalAddress": {
      "country": "RW",
      "subnationalDivisionL1": "RW-01",
      "subnationalDivisionL1Text": "City of Kigali",
      "addressLocalityText": "Kigali"
    },
    "tin": "987654322",
    "businessType": "Trading Company",
    "contactDetails": {
      "legalRepresentative": "Jane Smith",
      "contactPhoneNumber": "+250788999888",
      "contactEmail": "contact@rwandaexport.rw"
    }
  },
  "originatingOperation": [4],
  "inputLot": [
    {
      "lotNumber": "LOT-RW-2024-001"
    },
    {
      "lotNumber": "LOT-RW-2024-002"
    }
  ],
  "taxPaid": [
    {
      "taxType": "Processing Tax",
      "taxAmount": 2000.00,
      "currency": "USD"
    }
  ],
  "dateSealed": "2024-03-25",
  "dateShipped": "2024-03-27",
  "dateIn": "2024-03-22",
  "transportationMethod": "Truck",
  "transportationRoute": "Huye to Kigali",
  "transportCompany": "East Africa Logistics",
  "responsibleStaff": "Alice Brown, Processing Manager",
  "exportCertificateId": "RW-EXP-2024-001"
}
